version: '3.7'

services: 
  app:
    build:
      context: .
      dockerfile: ./docker/webserver.dockerfile
    image: 'laravelapp'
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
    environment:
      MYSQL_DATABASE: 'todo'
      MYSQL_USER: 'root'
      MYSQL_ROOT_USER: 'root'
      MYSQL_ROOT_PASSWORD: ""
    links:
      - db
    depends_on:
      - db
  db:
    image: mysql:latest
    restart: always
    ports: 
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'todo'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: ""
    volumes:
      - ./db:/var/lib/mysql